apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-client-rabbit
  name: grpc-client-rabbit
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client-rabbit
  strategy: {}
  template:
    metadata:
      labels:
        app: grpc-client-rabbit
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/grpc-client-rabbit
        name: grpc-client-rabbit
        resources: {}
      - image: carlostex/rabbitmq-client
        name: rabbitmq-client
        resources: {}
status: {}
--- #segundo cliente
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-client-pubsub
  name: grpc-client-pubsub
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client-pubsub
  strategy: {}
  template:
    metadata:
      labels:
        app: grpc-client-pubsub
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/grpc-client-pubsub
        name: grpc-client-pubsub
        resources: {}
      - image: carlostex/pubsub-client
        name: pubsub-client
        resources: {}
status: {}
--- #tercer cliente (1)
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-client-kafka
  name: grpc-client-kafka
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client-kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: grpc-client-kafka
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/grpc-client-kafka
        name: grpc-client-kafka
        resources: {}
      - image: carlostex/grpc-client-kafka
        name: kafka-client
        resources: {}
status: {}
--- #workers
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq-worker
  name: rabbitmq-worker
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-worker
  strategy: {}
  template:
    metadata:
      labels:
        app: rabbitmq-worker
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/rabbitmq-worker
        name: rabbitmq-worker
        resources: {}
status: {}
--- #segundo workers
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pubsub-worker
  name: pubsub-worker
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-worker
  strategy: {}
  template:
    metadata:
      labels:
        app: pubsub-worker
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/pubsub-worker
        name: pubsub-worker
        resources: {}
status: {}
--- #tercer workers
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-worker
  name: kafka-worker
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-worker
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-worker
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/kafka-worker
        name: kafka-worker
        resources: {}
status: {}
--- #servicios
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-client-rabbit
  name: grpc-client-rabbit
  namespace: squidgame
spec:
  ports:
  - port: 3000
    name: grpc11
    protocol: TCP
    targetPort: 3001
  - port: 9001
    name: grpc12
    protocol: TCP
    targetPort: 9001
  selector:
    app: grpc-client-rabbit
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-client-pubsub
  name: grpc-client-pubsub
  namespace: squidgame
spec:
  ports:
  - port: 3000
    name: grpc21
    protocol: TCP
    targetPort: 3002
  - port: 9002
    name: grpc22
    protocol: TCP
    targetPort: 9002
  selector:
    app: grpc-client-pubsub
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-client-kafka
  name: grpc-client-kafka
  namespace: squidgame
spec:
  ports:
  - port: 3000
    name: grpc31
    protocol: TCP
    targetPort: 3003
  - port: 9003
    name: grpc32
    protocol: TCP
    targetPort: 9003
  selector:
    app: grpc-client-kafka
  type: ClusterIP
status:
  loadBalancer: {}
--- #servicios worker
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-worker
  name: rabbitmq-worker
  namespace: squidgame
spec:
  selector:
    app: rabbitmq-worker
  ports:
  - port: 5672
    name: a1
    protocol: TCP
    targetPort: 5672
  - port: 27017
    name: a2
    protocol: TCP
    targetPort: 27017
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pubsub-worker
  name: pubsub-worker
  namespace: squidgame
spec:
  selector:
    app: pubsub-worker
  ports:
  - port: 80
    name: b1
    protocol: TCP
    targetPort: 80
  - port: 27017
    name: b2
    protocol: TCP
    targetPort: 27017
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-worker
  name: kafka-worker
  namespace: squidgame
spec:
  selector:
    app: kafka-worker
  ports:
  - port: 29092
    name: c1
    protocol: TCP
    targetPort: 29092
  - port: 27017
    name: c2
    protocol: TCP
    targetPort: 27017
  type: ClusterIP
status:
  loadBalancer: {}