apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy: {}
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/grpc-client-rabbit
        name: grpc-client-rabbit
        ports:
          - containerPort: 3001
        resources: {}
      - image: carlostex/rabbitmq-client
        name: rabbitmq-client
        ports:
          - containerPort: 9001
        resources: {}
      - image: carlostex/rabbitmq-worker:latest
        name: rabbitmq-worker
        resources: {}
      - image: rabbitmq:3-management-alpine
        name: rabbitmqs
        ports:
            - containerPort: 5672
            - containerPort: 15672
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/grpc-client-kafka
        name: grpc-client-kafka
        ports:
          - containerPort: 3003
        resources: {}
      - image: carlostex/kafka-client
        name: kafka-client
        ports:
          - containerPort: 9003
        resources: {}
      - image: carlostex/kafka-worker:latest
        name: kafka-worker
        resources: {}
      - image: bashj79/kafka-kraft
        name: kafkabr
        ports:
          - containerPort: 9092
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pubsub
  name: pubsub
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub
  strategy: {}
  template:
    metadata:
      labels:
        app: pubsub
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/grpc-client-pubsub
        name: grpc-client-pubsub
        ports:
          - containerPort: 3002
        resources: {}
      - image: carlostex/pubsub-client
        name: pubsub-client
        ports:
          - containerPort: 9002
        resources: {}
      - image: carlostex/pubsub-worker:latest
        name: pubsub-worker
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node
  name: node
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  strategy: {}
  template:
    metadata:
      labels:
        app: node
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/node-dashboard
        name: node-dashboard
        ports:
          - containerPort: 2500
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-service
  name: rabbitmq-service
  namespace: squidgame
spec:
  ports:
  - port: 3000
    name: rb1
    protocol: TCP
    targetPort: 3001
  selector:
    app: rabbitmq
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
  namespace: squidgame
spec:
  ports:
  - port: 3000
    name: rb2
    protocol: TCP
    targetPort: 3003
  selector:
    app: kafka
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pubsub-service
  name: pubsub-service
  namespace: squidgame
spec:
  ports:
  - port: 3000
    name: rb3
    protocol: TCP
    targetPort: 3002
  selector:
    app: pubsub
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-service
  name: node-service
  namespace: squidgame
spec:
  ports:
  - port: 2500
    name: rb4
    protocol: TCP
    targetPort: 2500
  selector:
    app: node
  type: ClusterIP
status:
  loadBalancer: {}