apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy: {}
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/grpc-client-rabbit
        name: grpc-client-rabbit
        ports:
          - containerPort: 3001
        resources: {}
      - image: carlostex/rabbitmq-client
        name: rabbitmq-client
        ports:
          - containerPort: 9001
        resources: {}
      - image: carlostex/rabbitmq-worker:latest
        name: rabbitmq-worker
        resources: {}
      - image: rabbitmq:3-management-alpine
        name: rabbitmqs
        ports:
            - containerPort: 5672
            - containerPort: 15672
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: carlostex/grpc-client-kafka
        name: grpc-client-kafka
        ports:
          - containerPort: 3002
        resources: {}
      - image: carlostex/rabbitmq-client
        name: kafka-client
        ports:
          - containerPort: 9002
        resources: {}
      - image: carlostex/rabbitmq-worker:latest
        name: kafka-worker
        resources: {}
      - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
        image: confluentinc/cp-kafka:latest
        name: kafka
        ports:
            - containerPort: 29092
        resources: {}
      - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
        image: confluentinc/cp-zookeeper:latest
        name: zookeeper
        ports:
            - containerPort: 2181
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-service
  name: rabbitmq-service
  namespace: squidgame
spec:
  ports:
  - port: 3000
    name: rb1
    protocol: TCP
    targetPort: 3001
  selector:
    app: rabbitmq
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
  namespace: squidgame
spec:
  ports:
  - port: 3000
    name: rb2
    protocol: TCP
    targetPort: 3002
  selector:
    app: kafka
  type: ClusterIP
status:
  loadBalancer: {}