apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: splitter
  namespace: squidgame
spec:
  service: rabbitmq-service
  backends:
  - service: pubsub-service
    weight: 100
#---